Repository YusufZiya23/EU10GROUP3HECTORWARE, pull requests merged in 2023-03, with the labels that each got.

#30 Login Functionality
  src/test/java/com/cydeo/pages/LoginPage_Fitim.java
  src/test/java/com/cydeo/step_definitions/LoginFitim_StepDefinitions.java
  src/test/resources/features/loginPage_Fitim.feature
Labels: enhancement

#39 Second scenario test couldn't pass, can you please check my mistake
  src/test/java/com/cydeo/step_definitions/Login_StepDefinitions.java
  src/test/java/com/cydeo/step_definitions/Talk_StepDefinitions_Anda.java
  src/test/resources/features/TalkByAnda.feature
Labels: help wanted

#40 Scenario: Verify that user is able to see “Incorrect conversation length” with red color if he enters invalid credentials, immediately after conversation name input box
  src/test/java/com/cydeo/pages/TalkPageByAnda.java
  src/test/java/com/cydeo/step_definitions/Talk_StepDefinitions_Anda.java
  src/test/resources/features/TalkByAnda.feature
Labels: bug
